apiVersion: v1
kind: Service
metadata:
  name: auth-admin
  namespace: autorena
spec:
  type: ClusterIP
  selector:
    app: auth-admin
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080 
