apiVersion: v1
kind: Service
metadata:
  name: auth-admin-postgres
  namespace: autorena
spec:
  selector:
    app: auth-admin-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432 