apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-admin-postgres-pv
  namespace: autorena
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/postgres-data/autorena-auth-admin-postgres 