apiVersion: v1
kind: Secret
metadata:
  name: auth-admin-secrets
  namespace: autorena
type: Opaque
data:
  db-user: YXV0aC1hZG1pbi11c2Vy # base64(auth-admin-user)
  db-password: YXV0aC1hZG1pbi1wYXNz # base64(auth-admin-pass)
  db-name: YXV0aC1hZG1pbi1kYg== # base64(auth-admin-db) 